### ISSUE TITLE
PE 2016.1.1 console-services logs openjdk invalid options

### ISSUE THREAD

**Issue by jessereynolds** [npwalker/control-repo-vagrant#2]
console-services-daemon.log mentions:

```
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=96m; support was removed in 8.0
OpenJDK 64-Bit Server VM warning: ignoring option PermSize=64m; support was removed in 8.0
WARNING: update already refers to: #'clojure.core/update in namespace: java-jdbc.sql, being replaced by: #'java-jdbc.sql/update
#
# java.lang.OutOfMemoryError: Java heap space
# -XX:OnOutOfMemoryError="kill -9 %p"
#   Executing /bin/sh -c "kill -9 4459"...
```

MaxPermSize and PermSize are not recognised by the OpenJDK, but maybe that's as intended. But as you can see it still ran out of heap when I tried adding a rule to a group in the NC.

**Comment by npwalker** [comment]
@jessereynolds I didn't see this when you submitted it.  I assume this issue no longer exists but let me know if it still does.  It would be a result of the hieradata provided in the actual control-repo in the virtual tier.
